name: oau_padi
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # For creating splash screen
  flutter_native_splash: ^2.3.2
  
  #For state management, dependency injection and routing
  get: ^4.6.6
  
  #For creating adaptable screen sizes and implementing fonts and designs to match screen
  flutter_screenutil: ^5.9.3


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/splash/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: "Nunito Sans"
      fonts:
        - asset: fonts/NunitoSans/NunitoSans-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/NunitoSans/NunitoSans-Black.ttf
          weight: 900
        - asset: fonts/NunitoSans/NunitoSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/NunitoSans/NunitoSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/NunitoSans/NunitoSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/NunitoSans/NunitoSans-Bold.ttf
          weight: 700
        - asset: fonts/NunitoSans/NunitoSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/NunitoSans/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: fonts/NunitoSans/NunitoSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/NunitoSans/NunitoSans-Medium.ttf
          weight: 500
        - asset: fonts/NunitoSans/NunitoSans-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: fonts/NunitoSans/NunitoSans-Regular.ttf
          weight: 400
        - asset: fonts/NunitoSans/NunitoSans-LightItalic.ttf
          weight: 300
          style: italic 
        - asset: fonts/NunitoSans/NunitoSans-Light.ttf
          weight: 300
        - asset: fonts/NunitoSans/NunitoSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/NunitoSans/NunitoSans-ExtraLight.ttf
          weight: 200
      
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_native_splash:
  color: "#53B175"
  image: assets/splash/splash1.png
  branding: assets/splash/splash2.png
  branding_mode: bottom
  #branding_bottom_padding: 24

  android_12:
    color: "#53B175"
    image: assets/splash/splash_center_image.png
    branding: assets/splash/splash2.png
  
  android: true
  ios: true

  android_gravity: center
  ios_content_mode: center

  fullscreen: true


